=== olgaloboda/XML-Individual-Project-UCL/DTD/bradbury.dtd
<!ELEMENT content (story+, addInfo?)>
<!ELEMENT story (header, text)>
<!ATTLIST story type CDATA #REQUIRED
                    title CDATA #REQUIRED>
<!-- Each header should consist of at least one 'meta' followed by at least one 'bibl'. -->
<!ELEMENT header (meta+, bibl+)>
<!ELEMENT meta (#PCDATA)>
<!-- In order to allow embedding meta tag's content dynamically, all the attributes are optional, i.e., implied. -->
<!ATTLIST meta author CDATA #IMPLIED
                              source CDATA #IMPLIED
                              lecturer CDATA #IMPLIED
                              module CDATA #IMPLIED>
<!ELEMENT bibl (#PCDATA | title | author | date | desc)*>
<!ELEMENT title (#PCDATA)>
<!-- Ray Bradbury's collections are heterogeneous, thinking about further markup, title classifies to which aspect of Ray Bradbury's work a particular text relates. -->
<!ATTLIST title level (a | m | j | s | u) #REQUIRED>
<!ELEMENT author (persName)>
<!ELEMENT desc (#PCDATA  | geogName | date)*>
<!ATTLIST desc of CDATA #IMPLIED>

<!ELEMENT text (p+)>
<!ELEMENT p (#PCDATA | reference | persName | sp | repetition | date | geogName | onomatopoeia |
                               metaphor | epithet | anaphora  | enumeration | simile | epiphora | 
                               zeugma | climax | personification | metonymy | break_in_the_narrative | 
                               hyperbole | periphrasis | asyndeton  | attachment | emph)*>

<!ELEMENT sp (#PCDATA | reference | enumeration | orgName | break_in_the_narrative | persName | 
                              repetition | anaphora | address | periphrasis | simile | climax | hyperbole | metaphor | event |
                              personification | geogName | asyndeton | attachment | emph)*>

<!-- Tropes -->
<!ELEMENT epithet (#PCDATA)>
<!-- 
    As the tags' category is known (in this example, it is trope), the attribute's value is fixed. 
    Attribute 'category' allows extracting by means of xslt either all tropes or figures of speech without enumerating all possible tropes or figures from the document. 
    'Device' allows extracting all tropes and figures simultaneously, and, it also shows another way of embedding fixed content. Usually this way is used to provide several predefined options to the content.
    'Ref' helps to extract xslt content of, for example, 'epithet' with the relation to what epithet refers.
-->
<!ATTLIST epithet category CDATA #FIXED "trope"
                    device (stylistic) #REQUIRED
                    ref CDATA #REQUIRED>
<!ELEMENT hyperbole (#PCDATA | reference)*>
<!ATTLIST hyperbole category CDATA #FIXED "trope"
                    device (stylistic) #REQUIRED>
<!ELEMENT metaphor (#PCDATA | date | epithet | personification | zeugma | enumeration | 
                                          simile | periphrasis | repetition | hyperbole | 
                                          reference)*>
<!ATTLIST metaphor category CDATA #FIXED "trope"
                                       device (stylistic) #REQUIRED>
<!ELEMENT metonymy (#PCDATA | epithet)*>
<!ATTLIST metonymy category CDATA #FIXED "trope"
                    device (stylistic) #REQUIRED
                    ref CDATA #REQUIRED>
<!ELEMENT onomatopoeia (#PCDATA)>
<!ATTLIST onomatopoeia category CDATA #FIXED "trope"
                    device (stylistic) #REQUIRED>                   
<!ELEMENT personification (#PCDATA | metonymy | onomatopoeia)*>
<!ATTLIST personification category CDATA #FIXED "trope"
                                               device (stylistic) #REQUIRED>
                          
<!ELEMENT zeugma (#PCDATA | epithet)*>
<!ATTLIST zeugma category CDATA #FIXED "trope"
                                   device (stylistic) #REQUIRED>
                 
<!--Figures of speech -->
<!ELEMENT anaphora (#PCDATA | metaphor | reference | repetition | zeugma | simile | hyperbole | geogName | enumeration)*>
<!ATTLIST anaphora category CDATA #FIXED "figure_of_speech"
                                      device (stylistic) #REQUIRED>
<!ELEMENT asyndeton EMPTY>
<!ATTLIST asyndeton category CDATA #FIXED "figure_of_speech"
                    device (stylistic) #REQUIRED>
<!ELEMENT attachment (#PCDATA)>
<!ATTLIST attachment category CDATA #FIXED "figure_of_speech"
                                         device (stylistic) #REQUIRED>
<!ELEMENT break_in_the_narrative (#PCDATA | reference)*>
<!ATTLIST break_in_the_narrative category CDATA #FIXED "figure_of_speech"
                                                              device CDATA #FIXED "stylistic"> 
<!ELEMENT enumeration (#PCDATA | simile | zeugma)*>
<!ATTLIST enumeration category CDATA #FIXED "figure_of_speech"
                                            device (stylistic) #REQUIRED>
<!ELEMENT epiphora (#PCDATA | reference | parallelism)*>
<!ATTLIST epiphora category CDATA #FIXED "figure_of_speech"
                                     device (stylistic) #REQUIRED>                                 
<!ELEMENT periphrasis (#PCDATA | metonymy)*>
<!ATTLIST periphrasis category CDATA #FIXED "figure_of_speech"
                                         device (stylistic) #REQUIRED>
<!ELEMENT climax (#PCDATA | epithet | reference | onomatopoeia)*>
<!ATTLIST climax category CDATA #FIXED "figure_of_speech"
                                device (stylistic) #REQUIRED>
<!ELEMENT parallelism (#PCDATA)>
<!ATTLIST parallelism category CDATA #FIXED "figure_of_speech"
                                         device (stylistic) #REQUIRED>                 
<!ELEMENT reference (#PCDATA)>
<!ATTLIST reference type (anaphoric | cataphoric) #REQUIRED
                                      to CDATA #IMPLIED>
<!ELEMENT simile (#PCDATA | onomatopoeia)*>
<!ATTLIST simile category CDATA #FIXED "figure_of_speech"
                                device (stylistic) #REQUIRED>
                 
<!-- Rhetorical device -->
<!ELEMENT repetition (#PCDATA | reference)*>
<!ATTLIST repetition device (rhetorical) #REQUIRED>

<!-- Proper nouns on denoting place, event, organisation and date. -->
<!-- 
    Even though address can consist of other information apart from house number and street, such as postcode, for example, 
    the accuracy of this markup analysis wasn't distorted with hypothetical elements which weren't met during markup process. 
    The same concerns other tags within this category (i.e., proper nouns on denoting place, event, organisation and date) as well.
-->
<!ELEMENT address (house_number, street)>
<!ATTLIST address type CDATA #IMPLIED>
<!ELEMENT house_number (#PCDATA)>
<!ELEMENT street (#PCDATA)>

<!ELEMENT date (month | year)*>
<!ATTLIST date type CDATA #IMPLIED>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ATTLIST year category CDATA #IMPLIED>

<!ELEMENT event (#PCDATA)>

<!ELEMENT geogName (region | geogFeat | planet)*>
<!ATTLIST geogName type CDATA #IMPLIED>
<!ELEMENT region (#PCDATA)>
<!ATTLIST region type CDATA #IMPLIED
                    location CDATA #IMPLIED>
<!ELEMENT geogFeat (#PCDATA)>
<!ELEMENT planet (#PCDATA)>

<!ELEMENT orgName (#PCDATA | geogName)*>
<!ATTLIST orgName type CDATA #IMPLIED>

<!-- TEI tags -->
<!-- It was important to predefine different options for persName leaving the structure of its content fixed. -->
<!ELEMENT persName ((persTitle?, forename?, surname) | (persTitle, forename, surname) | (persTitle, forename?, surname) | 
                                             (persTitle?, forename, surname?))>
<!-- As persName refers to fictional characters and real people, persName's attribute 'type' enables to separate fictional characters from real people. -->
<!ATTLIST persName type CDATA #IMPLIED
                                        who CDATA #REQUIRED>
<!ELEMENT persTitle (#PCDATA)>
<!ELEMENT forename (#PCDATA)>
<!ELEMENT surname (#PCDATA)>

<!ELEMENT birth (#PCDATA)>
<!ATTLIST birth of CDATA #REQUIRED>
<!ELEMENT death (#PCDATA)>
<!ATTLIST death of CDATA #REQUIRED>

<!ELEMENT emph (#PCDATA | metaphor)*>
<!ATTLIST emph for CDATA #IMPLIED>

<!-- Additional elements -->
<!-- Additional information should consist of at least one paragraph and not fixed number of list. 'list' is optional, whereas at least one 'para' is required. -->
<!ELEMENT addInfo ((para+, list*), (list*, para+))>
<!-- 
    This defines the 'type' of addInfo as additional information may relate to different aspects, such as references, biographies, acknowledgements, text analyses, interviews, related articles and so on. 
    Although this case related to bigraphy only, non-defined attribute is important for flexible markup of other stories in future.
-->
<!ATTLIST addInfo type CDATA #IMPLIED
                                  source CDATA #REQUIRED>
<!ELEMENT para (#PCDATA | persName | birth | death | bibl)*>
<!ELEMENT list (bibl+)>

=== olgaloboda/XML-Individual-Project-UCL/XML/AllStories.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Doctype defines relevance to identified dtd structure with 'content' as a root element. -->
<!DOCTYPE content SYSTEM "../DTD/bradbury.dtd">

<!-- This associates XSLTs with xml. -->
<?xml-stylesheet type="text/xsl" href="../XSLT/bradburyBiography.xsl"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/Coloured.xsl"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/Miscellaneous.xsl"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/ReadAll.xsl"?>
<?xml-stylesheet type="text/xsl" href="../XSLT/Stylistics.xsl"?>

<!-- Content consists of three stories. -->
<content>
    
        <story type="short story" title="The Pedestrian">
        <!-- 
            'header includes technical information which is either displayed (bibl) or hidden being empty (meta).
            'meta' inserts metadata which is a reference to document details. 'bibl' displays story's title, year (if mentioned) and author's name and surname.
        -->
        <header>
            <meta author="Olga Loboda"/>
            <meta module="INSTG037"/>
            <meta lecturer="Simon Mahony"/>
            <meta source="http://mikejmoran.typepad.com/files/pedestrian-by-bradbury-1.pdf"/>
            <bibl>
                <title level="a">The Pedestrian</title>
                <date>
                    <year>1951</year>
                </date>
                <author>
                    <persName type="author" who="Ray Bradbury">
                        <forename>Ray</forename>
                        <surname>Bradbury</surname>
                    </persName>
                </author>
            </bibl>
        </header>
        
        <!-- Text consists of paragraphs with dynamic content in it. The children of the tags related to tropes and figures of speech can't be predefined. -->
        <text>

            <p>
                <metaphor category="trope" device="stylistic">To enter out into that silence</metaphor> that was the city at eight o'clock of a 
                <epithet category="trope" device="stylistic" ref="evening">misty</epithet> evening in
                <date>
                    <month>November</month>
                </date>, to put your feet upon that buckling concrete walk,
                <metaphor category="trope" device="stylistic">to step over grassy seams and make your way, hands in pockets, through the silences</metaphor>, that was what 
                <persName type="character" who="Leonard Mead">
                    <persTitle>Mr.</persTitle>
                    <forename>Leonard</forename>
                    <surname>Mead</surname>
                </persName> most dearly loved to do.
                <reference type="anaphoric" to="Leonard Mead">He</reference> would stand upon the corner of an intersection and peer down long moonlit avenues of 
                sidewalk in four directions, deciding which way to go, but it really made no difference; 
                <reference type="anaphoric" to="Leonard Mead">he</reference> was alone in this world of 
                <date type="fictional">
                    <year category="AD">A.D. 2053</year>
                </date>, or as good as alone, and with a final decision made,
                <asyndeton device="stylistic" category="figure_of_speech"/>a path selected
                <reference type="anaphoric" to="Leonard Mead">he</reference> would stride off, sending patterns of frosty air before him 
                <simile category="figure_of_speech" device="stylistic">like the smoke of a cigar</simile>. 
            </p>

            <p>Sometimes
                <reference type="anaphoric" to="Leonard Mead">he</reference> would walk for hours and miles and return only at midnight to his house. And on his way
                <reference type="anaphoric" to="Leonard Mead">he</reference> would see the cottages and homes with their dark windows, and it was not unequal to 
                walking through a graveyard where only the faintest glimmers of firefly light appeared in flickers behind the windows. Sudden 
                <periphrasis category="figure_of_speech" device="stylistic">gray phantoms</periphrasis> seemed to manifest upon inner room walls where a curtain 
                was still undrawn against the night, or there were whisperings and murmurs where a window in a 
                <epithet category="trope" device="stylistic" ref="building">tomblike</epithet> building was still open. 
            </p>

            <p>
                <persName type="character" who="Leonard Mead">
                    <persTitle>Mr.</persTitle>
                    <forename>Leonard</forename>
                    <surname>Mead</surname>
                </persName> would 
                <enumeration category="figure_of_speech" device="stylistic">pause, cock his head, listen, look, and march on</enumeration>, his feet making no noise on the 
                <epithet category="trope" device="stylistic" ref="walk">lumpy</epithet> walk. For long ago
                <reference type="anaphoric" to="Leonard Mead">he</reference> had wisely changed to sneakers when strolling at night, because the dogs in intermittent squads 
                would parallel his journey with barkings if he wore hard heels and lights might click on and faces appear and an entire street be startled by the passing of a 
                <periphrasis category="figure_of_speech" device="stylistic">lone figure</periphrasis>, himself, in the early 
                <date>
                    <month>November</month>
                </date> evening. 
            </p>

            <p>On this particular evening 
                <reference type="anaphoric" to="Leonard Mead">he</reference> began his journey in a westerly direction, toward the hidden sea. There was a good 
                <metaphor category="trope" device="stylistic">
                    <epithet category="trope" device="stylistic" ref="frost">crystal</epithet> frost in the air;
                    <hyperbole device="stylistic" category="trope">
                        <reference type="anaphoric" to="frost">it</reference> cut the nose and made the lungs blaze</hyperbole> 
                    <simile category="figure_of_speech" device="stylistic">like a Christmas tree inside</simile>; you could feel the
                    <epithet device="stylistic" category="trope" ref="light">cold</epithet> light going on and off, all the 
                    <periphrasis device="stylistic" category="figure_of_speech">branches</periphrasis> filled with invisible snow
                </metaphor>.
                <reference type="anaphoric" to="Leonard Mead">He</reference> listened to the faint push of his soft shoes through autumn leaves with satisfaction, and 
                <onomatopoeia category="trope" device="stylistic">whistled</onomatopoeia> a cold quiet
                <onomatopoeia category="trope" device="stylistic">whistle</onomatopoeia> between his teeth, occasionally picking up a leaf as
                <reference type="anaphoric" to="Leonard Mead">he</reference> passed, examining its skeletal pattern in the infrequent lamplights as 
                <reference type="anaphoric" to="Leonard Mead">he</reference> went on, smelling its rusty smell. 
            </p>

            <p>
                <sp>"Hello, in there,"</sp> 
                <reference type="anaphoric" to="Leonard Mead">he</reference> 
                <onomatopoeia device="stylistic" category="trope">whispered</onomatopoeia> to every house on every side as 
                <reference type="anaphoric" to="Leonard Mead">he</reference> moved.
                <sp>"What's up tonight on 
                    <enumeration category="figure_of_speech" device="stylistic">Channel 4, Channel 7, Channel 9</enumeration>? Where are the cowboys rushing, and do I see 
                    <orgName>
                        <geogName>
                            <region type="country">the United States</region>
                        </geogName>Cavalry
                    </orgName> over the next hill to the rescue?" 
                </sp>
            </p>

            <p>The street was 
                <zeugma category="trope" device="stylistic">silent and long and empty</zeugma>, with only his shadow moving 
                <simile category="figure_of_speech" device="stylistic">like the shadow of a hawk</simile> in midcountry. If
                <reference type="anaphoric" to="Leonard Mead">he</reference> closed his eyes and stood very still, 
                <epithet category="trope" device="stylistic" ref="Leonard Mead">frozen</epithet>, 
                <reference type="anaphoric" to="Leonard Mead">he</reference> could imagine himself upon the center of a plain, a wintry,
                <asyndeton device="stylistic" category="figure_of_speech"/> windless
                <geogName type="desert">
                    <region type="state">Arizona</region>
                    <geogFeat>desert</geogFeat>
                </geogName>with no house in a thousand miles, and only 
                <periphrasis category="figure_of_speech" device="stylistic">dry river beds</periphrasis>, the streets, for company. 
            </p>

            <p>
                <sp>"What is it now?"</sp>
                <reference type="anaphoric">he</reference> asked the
                <metonymy device="stylistic" category="trope" ref="people">houses</metonymy>, noticing his wrist watch. 
                <sp>"Eight-thirty P.M.? Time for a dozen assorted murders? A quiz? A revue? A comedian falling off the stage?"</sp>
            </p>

            <p>Was that a 
                <onomatopoeia device="stylistic" category="trope">murmur</onomatopoeia> of laughter from within a moon-white house?
